apiVersion: v1
kind: Secret
metadata:
  name: evolvex-agent-secret
type: Opaque
stringData:
  webhook-secret: {{ required "evolvex.webhookSecret is required" .Values.evolvex.webhookSecret | quote }}
  signoz-ingestion-key: {{ .Values.signoz.ingestionKey | quote }}
  evolvex-collector-key: {{ .Values.evolvex.collectorKey | quote }}
